import type { Metadata } from 'next'
import { metadataForCmsPage } from '@/lib/seo/metadata'
import { getPublishedPageBySlug } from '@/lib/page-builder/publicPages'
import { DirectoryHero } from '@/components/public/DirectoryHero'
import { OpportunityFilters } from '@/components/public/filters/OpportunityFilters'
import { listPublishedOpportunities,parseOpportunityFilters } from '@/lib/content/opportunities'
function toParams(o:Record<string,string|string[]|undefined>){const p=new URLSearchParams();for(const[k,v]of Object.entries(o))if(typeof v==='string')p.set(k,v);return p}
export async function generateMetadata():Promise<Metadata>{return metadataForCmsPage(await getPublishedPageBySlug("opportunities"))}
export default async function OpportunitiesPage({searchParams}:{searchParams:Promise<Record<string,string|string[]|undefined>>}){const f=parseOpportunityFilters(toParams(await searchParams));const [items,allItems]=await Promise.all([listPublishedOpportunities(f),listPublishedOpportunities({openOnly:false})]);const showFilters=allItems.length>=4;return <><DirectoryHero slug={"opportunities"} eyebrow={"Opportunities"} title={"Opportunities"} description={"Internships, research positions, fellowships, and funding shared with the club. Check each listing for requirements and deadlines."} imageSlug={"opportunities-research-networking"}/><section className="directory"><div className="shell">{showFilters&&<OpportunityFilters type={f.type}/>}{items.length?<div className="card-grid">{items.map((o:any)=><article className="content-card" key={o.id}><div className="content-card__actions"><p className="eyebrow">{o.opportunity_type}</p></div><h2>{o.title}</h2><p><strong>{o.organization}</strong>{o.location?` · ${o.location}`:''}</p><p>{o.description}</p>{o.deadline&&<p>Deadline: <strong>{new Date(`${o.deadline}T12:00:00`).toLocaleDateString()}</strong></p>}<a href={o.url} target="_blank" rel="noreferrer">Open opportunity ↗</a></article>)}</div>:<div className="empty-state"><h2>No opportunities yet.</h2><p>There are no listings right now. We will add them here as members share them.</p></div>}</div></section></>}
